# Default values for skydns.
# This is a YAML-formatted file
replicas: 1
version: v17
color: FFFF66
k8sapp: kube-dns
kubedns_image: "gcr.io/google_containers/kubedns-amd64:1.5"
kubedns_cpu_lim: 100m
kubedns_mem_lim: 200Mi
kubedns_cpu_req: 100m
kubedns_mem_req: 100Mi
healthz_image: "gcr.io/google_containers/exechealthz-amd64:1.0"
healthz_cpu_lim: 10m
healthz_mem_lim: 20Mi
healthz_cpu_req: 10m
healthz_mem_req: 20Mi
healthz_port: 8080
healthz_delay: 60
healthz_timeout: 5
healthz_success_thresh: 1
healthz_failure_thresh: 5
readiness_port: 8081
readiness_delay: 30
readiness_timeout: 5
dnsmasq_image: "gcr.io/google_containers/kube-dnsmasq-amd64:1.3"
dnsmasq_port: 53
dns_domain: cluster.local
cluster_ip: 10.100.0.10
tolerations:
 # - key: taintKey
 #   value: taintValue
 #   operator: Equal
 #   effect: NoSchedule
scheduling:
  affinity:
    node:
      type: #requiredDuringSchedulingIgnoredDuringExecution
      labels:
      # - key: iamalabelkey
      #   operator: In
      #   values: ["value1", "value2"]
