# Default values for nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# gcsfuse properties
####################
# bucketName     : this is the bucket name you want to mount on GCS
# mountDirectory : this is the location on the pod that you want to mount the GCS bucket

gcsfuse:
  bucketName: changeme
  mountDirectory: /usr/share/nginx/html

# nginx properties
##################
# rootDirectory : this is the root directory for nginx to set itself up at
# autoIndex     : this is for the nginx server to give a traditional directory
#   listing or not for it's folder structure, value can either be "on" or "off",

nginx:
  rootDirectory: /usr/share/nginx/html
  autoIndex: off

# lbex properties
#################
# enabled : this enables the lbex load balancer for this deployment
# port : this is the lbex port that will be used for this deployment
# for more information, visit : https://github.com/samsung-cnct/lbex/blob/master/README.md

lbex:
  enabled: false
  port: 9080

replicaCount: 1
image:
  repository: quay.io/samsung_cnct/gsbucketserver
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  externalPort: 80
  internalPort: 80
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

tolerations:
 # - key: taintKey
 #   value: taintValue
 #   operator: Equal
 #   effect: NoSchedule
scheduling:
  affinity:
    node:
      type: #requiredDuringSchedulingIgnoredDuringExecution
      labels:
      # - key: iamalabelkey
      #   operator: In
      #   values: ["value1", "value2"]
