apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-lego
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-kube-lego"
  annotations:
    "helm.sh/created": {{.Release.Time.Seconds | quote }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
        component: "{{.Release.Name}}-kube-lego"
        # Required for the auto-create kube-lego-nginx service to work.
        app: kube-lego
    spec:
      containers:
        - name: kube-lego
          image: {{ .Values.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: LEGO_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: kube-lego
                  key: lego.email
            - name: LEGO_URL
              valueFrom:
                configMapKeyRef:
                  name: kube-lego
                  key: lego.url
            - name: LEGO_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LEGO_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 1