---
replicas: 1
color: E5CCFF
prometheus_image: "prom/prometheus:v1.2.1"
prometheus_port: 9090
prometheus_node_port: 30360
storage_local_retention: '876000h'
kube_apiserver: "localhost:8001"
kube_controller_manager: "127.0.0.1:10252"
kube_scheduler: "127.0.0.1:10251"
etcd_target: "127.0.0.1:4001"
master_cadvisor: "127.0.0.1:8094"
etcd_cadvisor: "127.0.0.1:8094"
kubelet_cadvisor_target: "127.0.0.1:11111"
pushgateway_image: "prom/pushgateway:0.3.0"
pushgateway_port: 9091
pushgateway_node_port: 30362
config_dir: /etc/prometheus/
data_dir: /prometheus
storage_class: anything
storage_size: 1Gi
