Vault:
  Image: "quay.io/samsung_cnct/vault"
  ImageTag: "0.5.2"
  ImagePullPolicy: "Always"
  Component: "vault"

  NodePort: 32443

  Backend:
    Type: "consul"
    Address: "consul.kube-system.svc.cluster.io:8500"
    Scheme: "http"
    Token: "token"

  Replicas: 1
  Cpu: "512m"
  Memory: "200Mi"

  Tls:
    Cert: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURuRENDQVlRQ0FRRXdEUVlKS29aSWh2Y05BUUVMQlFBd1ZqRUxNQWtHQTFVRUJoTUNWVk14Q3pBSkJnTlYKQkFnTUFsZEJNUkF3RGdZRFZRUUhEQWRUWldGMGRHeGxNUk13RVFZRFZRUUtEQXBUWVcxemRXNW5VMFJUTVJNdwpFUVlEVlFRRERBb3FMbXh2WTJGc0xtbHZNQjRYRFRFMk1USXlNVEU0TWpRd05Gb1hEVEUzTURFeU1ERTRNalF3Ck5Gb3dWakVMTUFrR0ExVUVCaE1DVlZNeEN6QUpCZ05WQkFnTUFsZEJNUkF3RGdZRFZRUUhEQWRUWldGMGRHeGwKTVJNd0VRWURWUVFLREFwVFlXMXpkVzVuVTBSVE1STXdFUVlEVlFRRERBb3FMbXh2WTJGc0xtbHZNSUdmTUEwRwpDU3FHU0liM0RRRUJBUVVBQTRHTkFEQ0JpUUtCZ1FDK2I1MWdIc2EyWWJEN0ZMMDN2d2J4R001TDdrYUdDbGZtCkFXbFo2aGkxbER5Z00wMTlNVDFyNHRiY0RlTFN4VFE3QUE5VkhxdW9HMHBmTzM2UUNHMjhRbVZ4U0dDZ3hhS2UKL0dYYzJ4OWhjd09DZ01EdktGMHRlZW44aXo2Z1dsbXVZakJoSDZPRlNLRkRKQ1RVVEprZStpWFkrbkh3d3lwcQpleko5NHdldlpRSURBUUFCTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElDQVFDWDVPdWd0VXNGMmsxemFvY3pBQW1EClNVemdQRjRGUEhBSUJPS0xwRTJYQmMyN25pZk4vWnlFVkFOMHRRWmZMSlBXeWwwYWdZclZGeklwekhpTC94R2IKOHp1aTBmUDRKVFUyS1dDSmFxSE5RMHYxSTRuYzBzdUpYZ1A4RlhQOFU3QmhWakhXcVgvNDBLVzNCbXlqNGdpMApteS9CV1BKV2RGWi9lTG43M3JaWU45a2tzNHBxODFpcTJYOUxmbnBoTmNRTlJlNC84UGtSUXJvY3B5b2hPS0hvCkJtREtVR3REQ1pjNUpNZTRGa0dJb0h2MWZIUlVkUG4yVzAxWkNZMHVST2xRUlg0MjN2dDljZmQzblZRSDQ4Qm0KZkRhaHhQV1VYSlJIc083U21nRWpmaXpwSnRLN3I1UktWUk5ydldqVUlFbml3VjVDWUMvRFdrN2xGRXB2V3VzdgoweXFWVjhRY3U1VVZVWGlkVGQ1M3c4WlpMTXUwNGJuWkF0Ym9Edks5a3A3TUViOGJHRFNZWmRjUTF0cnZ6c3ArCkhjelRhTTFudXdEU0hHdHdxcS9BVzNSb3J0NCtTSDlhWEFBWmpZU2QyVWo5M3FudGZmcmY5S1R4WG1zVEozOG8KNVl6bElScERNYmVNRVlVQWc4RzAvdnZvcFUxZllhRjdyMzJPRkVEZzlGbW5DZ2IxZnFRbWJoOFczRE1FaGJhQgpmTFZHb095VlYyYlg5TFZkSy9CbW1IZlpaYkRvUC9RYVR0QlJoT3BPOUt1WUw5WG5adGRTckIxTTE5cnRSM0hwCmYyaUpUZkZhczJUNE1XZGJ6UU1xYklzTEovbnBBWjhJelM5ZnlqTlhod0xRaGViamFLdTNmc1ZiQVBNS1JvV08KRnNGbGNpVDA2VUs5emtISkM4WTg3UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    Key: "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlDWEFJQkFBS0JnUUMrYjUxZ0hzYTJZYkQ3RkwwM3Z3YnhHTTVMN2thR0NsZm1BV2xaNmhpMWxEeWdNMDE5Ck1UMXI0dGJjRGVMU3hUUTdBQTlWSHF1b0cwcGZPMzZRQ0cyOFFtVnhTR0NneGFLZS9HWGMyeDloY3dPQ2dNRHYKS0YwdGVlbjhpejZnV2xtdVlqQmhINk9GU0tGREpDVFVUSmtlK2lYWStuSHd3eXBxZXpKOTR3ZXZaUUlEQVFBQgpBb0dBWHF1V0RPYS8yb01PUElPKzNTdTJBNzFWTVNJdkpRdVhUdHg4eHhvOVZtZHZEQ1QwN0x2QjBSUmZ3OTJUCldUeDREcXlrOHFmZ3BoMkxCM1RJSWtwT1lsODRvQUFNQVF0THhYYmt1K1F5RGdBVlBaYS96c2ZqODQydDBRUUQKUkRUZUl3Tyt0cGNiSkNrK2Q2cnNrU0FweEUzSHQ4VXBPYXkrelo4STJ1bVpHckVDUVFEN0JPRVZCamVNQzd4YgpuekdKcjVTMG9mWE1CTDBmakd5Zkswdkk1OUJ2ckYzTnpKY2Y0RDNTbWtKT3g5T2E2ZWVoNnRZcEVjKzRVeHBnClV1R0phL2lEQWtFQXdqYjhzVnQ0bVpJNlJDcEFBZmN2TXJYdFNwMko4b3FTNC9tQndhVTZweTE5RWZqSUtXMEMKTjQzOVJWa0N1emR1ZWh5N1BuNW4xdUlMSWVUNFU4c2o5d0pBVDNmLytqUDVxZkNkTlRSMDdtNFQyZ3ZjVVRhKwoyUm9QMldSUG5jOG1BZlREemIrVHFKZkplcjh6ZHRWMGZIckl4azRlZHVvWXBQWktSMngxMHBmSUdRSkJBSXRrCjZBMXI5NjFSMU53ajd2ajZMemdZZDQzOGNJeFNoWWQzQjNpelhOdXN2SDN2cjhwNzRRRjZ1ZlBTSlRHMllXYm4KeEVUZ2VTc3o1b1dYVDl6a2lwVUNRRmp6MDIyazcyTG5BZHBvc2o2QmxPVmdWNlZNcnlCL1k5TlJkSFhVSWdnQwpaOVMxbmlJTnptakhDQjZMZE1yUFh4Q1NjbStTWXUvbkpITHIrUy9NOGN3PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo="

  tolerations:
   # - key: taintKey
   #   value: taintValue
   #   operator: Equal
   #   effect: NoSchedule
  scheduling:
    affinity:
      node:
        type: #requiredDuringSchedulingIgnoredDuringExecution
        labels:
        # - key: iamalabelkey
        #   operator: In
        #   values: ["value1", "value2"]
